[[constraint]]
name = "github.com/ndau/chaincode"
version = "~v1.2"

[[constraint]]
name = "github.com/ndau/genesis"
version = "~v1.2"

[[constraint]]
name = "github.com/ndau/json2msgp"
version = "~v1.1"

[[constraint]]
name = "github.com/ndau/metanode"
version = "~v1.9"

[[constraint]]
name = "github.com/ndau/ndau"
version = "~v1.26"

[[constraint]]
name = "github.com/ndau/ndaumath"
version = "~v1.3"

[[constraint]]
name = "github.com/ndau/o11y"
version = "~v1.3"

[[constraint]]
name = "github.com/ndau/rest"
version = "~v0.1"

[[constraint]]
name = "github.com/ndau/system_vars"
version = "~v1.5"

[[constraint]]
name = "github.com/ndau/writers"
version = "~v1.1"

[[constraint]]
name = "github.com/alexflint/go-arg"
version = "v1.1"

[[constraint]]
name = "github.com/stretchr/testify"
version = "v1.7"

[[override]]
name = "github.com/attic-labs/graphql"
branch = "master"

[[override]]
name = "github.com/attic-labs/noms"
branch = "master"

[[override]]
name = "github.com/gofrs/uuid"
version = "~v3.2"

[[override]]
name = "github.com/tendermint/tendermint"
version = "=v0.32.3"

[[override]]
name = "github.com/tinylabs/msgp"
version = "v1.1.0"

[[override]]
# why do we do this meaningless thing, given that golang/x/* packages
# are specified by the go compiler? In short, Tendermint made some bad
# versioning choices, and this helps fix them.
# https://ndevtalk.slack.com/archives/CFT5J0N81/p1551689341081100
name = "golang.org/x/crypto"
