NodeRewardWebhookDelay = 10.0
PostgresConnection = "postgres://node@localhost:5432/ndau"
PostgresPasswordPath = "/image/postgres-node-pw"

[Features]
  # Feature heights for mainnet.  See docker-config-default.toml for more information.
  NoExchangeHoldsOnTransfer = 13_510
  NoKeysOnSetValidation = 13_510
  ResetUncreditedEAIOnCreditEAI = 13_510
  NodeActiveCheck = 31_025
  NoLeakyUpdateState = 31_025
  SequenceIncrementProtection = 31_025
  CreditEAIUnlocksAccounts = 31_025
  ApplyUncreditedEAI = 31_025
  FixEAIUnlockBug = 31_025
  TargetPrice9999 = 31_025
  SysvarValidityCheck = 31_025
  NodeRegistrationDate = 50_100
  # new features: change to a sane number before upgrading mainnet
  UpdateWAAUpdateDateInDetails = 1_000_000
