NodeRewardWebhookDelay = 10.0
PostgresConnection = "postgres://node@localhost:5432/ndau"
PostgresPasswordPath = "/image/postgres-node-pw"

[Features]
  # Block heights at which features becomes active.  Add more feature heights here as needed.
  # Use the other docker-config-*.toml files next to this one for network-specific height gating.
  # By default, all features are active at genesis, so no gates are listed in this default file.
  #
  # User code uses app.IsFeatureActive("FeatureName") to know whether a given feature is active.
  #
  # Typically we add new features and assign a "future" height to them.  We can change them just
  # before deploying to a network.  But in no case should we change any heights in this section
  # that are less than or equal to the network's current height, since those features need old
  # logic for playback compatibility.
